<a href="https://colab.research.google.com/github/AmritaSum/ProbabilityDistributions-ai1-fall2019/blob/master/elections_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
!pip install seaborn

In [0]:
%matplotlib inline
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import pandas as pd
import seaborn.apionly as sns # conda install seaborn or pip install seaborn

In [0]:
electoral_votes = pd.read_csv('https://raw.githubusercontent.com/AmritaSum/ProbabilityDistributions-ai1-fall2019/master/data/electoral_votes.csv')


In [0]:
electoral_votes = electoral_votes.set_index('State')


In [48]:
electoral_votes.head()

Votes
State            
California     55
Texas          38
New York       29
Florida        29
Illinois       20

In [0]:
predictwise=pd.read_csv('https://raw.githubusercontent.com/AmritaSum/ProbabilityDistributions-ai1-fall2019/master/data/predictwise.csv').set_index('States')

In [50]:
predictwise.head()

Obama  Romney  Votes
States                          
Alabama     0.000   1.000      9
Alaska      0.000   1.000      3
Arizona     0.062   0.938     11
Arkansas    0.000   1.000      6
California  1.000   0.000     55

In [0]:
simulations=np.random.uniform(size=(51,10000))


In [52]:
type(simulations)

numpy.ndarray

In [53]:
simulations.shape


(51, 10000)

In [54]:
print(simulations)

[[0.23509578 0.34847007 0.42597737 ... 0.81752458 0.53464149 0.26234158]
 [0.97777965 0.6014194  0.27193381 ... 0.81299985 0.08950614 0.04796535]
 [0.11423211 0.53959502 0.07817174 ... 0.58622489 0.34078177 0.28807902]
 ...
 [0.05403577 0.8903132  0.38810398 ... 0.15094333 0.26606729 0.00708375]
 [0.25738055 0.53520289 0.76624416 ... 0.16796763 0.69438602 0.62625429]
 [0.00153759 0.32497886 0.41404071 ... 0.0785296  0.59860704 0.80246791]]


In [55]:
plt.hist(simulations)

KeyboardInterrupt: ignored

Error in callback <function flush_figures at 0x7f4f0cd4f9d8> (for post_execute):


KeyboardInterrupt: ignored

In [0]:
simulations[0].shape

In [0]:
obama_votes=(simulations<predictwise.Obama.values.reshape(-1,1))* predictwise.Votes.values.reshape(-1,1)

In [0]:
obama_votes.shape

In [0]:
results=obama_votes.sum(axis=0)

In [0]:
print(obama_votes.shape)

In [58]:
np.sum(results>=269)

9970